name: Integration tests

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install php
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          extension-csv: intl,mbstring,json,bcmath
      - name: Install dependencies
        uses: php-actions/composer@v1
      - name: Unit tests
        env:
          MERCHANT_TOKEN: ${{ secrets.MERCHANT_TOKEN }}
          PAYEE_ID: ${{ secrets.PAYEE_ID }}
          MERCHANT_TOKEN_MOBILEPAY: ${{ secrets.MERCHANT_TOKEN_MOBILEPAY }}
          PAYEE_ID_MOBILEPAY: ${{ secrets.PAYEE_ID_MOBILEPAY }}
        run: ./vendor/bin/phpunit --configuration=./phpunit.xml.dist --bootstrap=./tests/bootstrap.php ./tests/ --coverage-clover=coverage.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: /tmp/swedbankpay.log
