name: Integration tests

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v1
      - name: Unit tests
        env:
          MERCHANT_TOKEN: ${{ secrets.MERCHANT_TOKEN }}
          PAYEE_ID: ${{ secrets.PAYEE_ID }}
        run: ./vendor/bin/phpunit --configuration=./phpunit.xml.dist --bootstrap=./tests/bootstrap.php ./tests/ --coverage-clover=coverage.xml
