name: Integration tests

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        uses: php-actions/phpunit@v1
        env:
          MERCHANT_TOKEN: ${{ secrets.MERCHANT_TOKEN }}
          PAYEE_ID: ${{ secrets.PAYEE_ID }}
